const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

export function createAudio() {
  let context = null, master = null, motor = null, motorGain = null, running = false, paused = false, muted = false, volume = .24, motifTimer = 0, motifStep = 0;
  const active = new Set(), motifSources = new Set();
  const audioClass = () => globalThis.AudioContext || globalThis.webkitAudioContext;
  const output = () => { if (master && context) master.gain.setTargetAtTime(muted || volume <= 0 ? 0 : volume, context.currentTime, .03); };
  function ensure() { if (context) return true; const AudioContextClass = audioClass(); if (!AudioContextClass) return false; try { context = new AudioContextClass(); master = context.createGain(); master.gain.value = 0; master.connect(context.destination); output(); return true; } catch (_) { context = null; master = null; return false; } }
  function unlock() { if (!ensure()) return false; try { const result = context.resume?.(); result?.catch?.(() => {}); return true; } catch (_) { return false; } }
  function tone(frequency, duration = .16, type = 'sine', gain = .05, when = null, slide = null, set = active) { if (!context || !master || muted || volume <= 0) return; const start = Math.max(context.currentTime + .004, when ?? context.currentTime + .004), oscillator = context.createOscillator(), envelope = context.createGain(); oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, start); if (slide) oscillator.frequency.exponentialRampToValueAtTime(Math.max(24, slide), start + duration); envelope.gain.setValueAtTime(.0001, start); envelope.gain.exponentialRampToValueAtTime(gain, start + .015); envelope.gain.exponentialRampToValueAtTime(.0001, start + duration); oscillator.connect(envelope).connect(master); oscillator.start(start); oscillator.stop(start + duration + .035); active.add(oscillator); set.add(oscillator); const clean = () => { oscillator.disconnect?.(); envelope.disconnect?.(); active.delete(oscillator); set.delete(oscillator); }; oscillator.addEventListener?.('ended', clean, { once: true }); return oscillator; }
  function clearMotif() { if (motifTimer) { globalThis.clearTimeout(motifTimer); motifTimer = 0; } for (const source of motifSources) { try { source.stop?.(); } catch (_) {} source.disconnect?.(); active.delete(source); } motifSources.clear(); }
  function scheduleMotif() { if (!running || paused || !context) return; const notes = [146.83, 185, 220, 277.18, 220, 185], now = context.currentTime + .04; const note = notes[motifStep++ % notes.length]; tone(note, .46, 'triangle', .018, now, note * 1.01, motifSources); motifTimer = globalThis.setTimeout(() => { motifTimer = 0; scheduleMotif(); }, 560); }
  function startMotor() { if (!context || motor) return; motor = context.createOscillator(); motorGain = context.createGain(); motor.type = 'sawtooth'; motor.frequency.value = 54; motorGain.gain.value = .012; motor.connect(motorGain).connect(master); motor.start(); active.add(motor); }
  function stopMotor() { if (!motor) return; try { motor.stop(); } catch (_) {} motor.disconnect?.(); motorGain?.disconnect?.(); active.delete(motor); motor = null; motorGain = null; }
  function start() { if (!unlock()) return false; if (running) return true; running = true; paused = false; motifStep = 0; startMotor(); scheduleMotif(); return true; }
  function pause() { clearMotif(); if (!context) return; paused = true; try { const result = context.suspend?.(); result?.catch?.(() => {}); } catch (_) {} }
  function resume() { if (!context || !running) return; paused = false; try { const result = context.resume?.(); result?.catch?.(() => {}); } catch (_) {} if (!motor) startMotor(); if (!motifTimer) scheduleMotif(); }
  function stop() { running = false; paused = false; clearMotif(); stopMotor(); for (const source of active) { try { source.stop?.(); } catch (_) {} source.disconnect?.(); } active.clear(); }
  function play(event) { if (!context && !unlock()) return false; const kind = typeof event === 'string' ? event : event?.type || event?.id || ''; if (muted || volume <= 0 || paused) return true; const now = context.currentTime; if (kind === 'jump') tone(210, .16, 'triangle', .055, now, 420); else if (kind === 'land') { tone(90, .1, 'square', .05, now, 55); tone(180, .07, 'sine', .03, now + .025); } else if (kind === 'dash') tone(160, .2, 'sawtooth', .06, now, 620); else if (kind === 'punch') tone(92, .12, 'square', .07, now, 48); else if (kind === 'shot') { tone(540, .1, 'triangle', .075, now, 170); tone(980, .08, 'sine', .035, now + .02); } else if (kind === 'hit') tone(74, .18, 'sawtooth', .08, now, 32); else if (kind === 'recall' || kind === 'armor-return') { [262, 392, 523].forEach((n, i) => tone(n, .26, 'triangle', .055, now + i * .07)); } else if (kind === 'relay') tone(660, .25, 'sine', .065, now, 990); else if (kind === 'boss-tell') tone(118, .42, 'triangle', .05, now, 74); else if (kind === 'boss-open') tone(310, .22, 'sine', .06, now, 560); else if (kind === 'enemy-down') tone(330, .18, 'square', .06, now, 100); else if (kind === 'clear') [392, 494, 659, 784].forEach((n, i) => tone(n, .34, 'triangle', .07, now + i * .11)); else if (kind === 'lose') tone(110, .5, 'sawtooth', .07, now, 42); else if (kind === 'denied') tone(105, .2, 'square', .045, now, 70); return true; }
  function update(run, dt = 0) { if (!running || paused || !run || !motor) return; const speed = Math.abs(Number(run.player?.vx) || 0); motor.frequency.setTargetAtTime(48 + speed * 7, context.currentTime, .08); motorGain.gain.setTargetAtTime(.01 + Math.min(.018, speed * .002), context.currentTime, .08); }
  function setVolume(value) { volume = clamp(Number(value) || 0, 0, 1); output(); }
  function setMuted(value) { muted = !!value; output(); }
  function dispose() { stop(); try { const result = context?.close?.(); result?.catch?.(() => {}); } catch (_) {} context = null; master = null; }
  return { unlock, setVolume, setMuted, start, pause, resume, stop, play, update, dispose };
}

export default createAudio;
