import * as THREE from 'three';

export const palette = { ivory: 0xe9e3d3, ivoryBright: 0xfff4d7, charcoal: 0x252a34, charcoalDeep: 0x111722, cobalt: 0x2f74cf, cobaltGlow: 0x50b9ff, yellow: 0xf2c84b, yellowHot: 0xffe477, rust: 0x9d563b, steel: 0x657486, hazard: 0xe7a52d, violet: 0x7252a8 };
const material = (color, options = {}) => new THREE.MeshStandardMaterial({ color, roughness: options.roughness ?? .62, metalness: options.metalness ?? .15, emissive: options.emissive ?? 0, emissiveIntensity: options.emissiveIntensity ?? 0, transparent: !!options.transparent, opacity: options.opacity ?? 1, ...(options.side ? { side: options.side } : {}) });
const box = (w, h, d, color, options = {}) => new THREE.Mesh(new THREE.BoxGeometry(w, h, d), material(color, options));
const joint = (radius = .14, color = palette.charcoal) => new THREE.Mesh(new THREE.SphereGeometry(radius, 12, 8), material(color, { metalness: .7, roughness: .35 }));
const armor = (w, h, d, color = palette.ivory) => { const shape = new THREE.Shape(); const c = Math.min(.055, w * .16, h * .16); shape.moveTo(-w / 2 + c, -h / 2); shape.lineTo(w / 2 - c, -h / 2); shape.lineTo(w / 2, -h / 2 + c); shape.lineTo(w / 2, h / 2 - c); shape.lineTo(w / 2 - c, h / 2); shape.lineTo(-w / 2 + c, h / 2); shape.lineTo(-w / 2, h / 2 - c); shape.lineTo(-w / 2, -h / 2 + c); shape.closePath(); const geometry = new THREE.ExtrudeGeometry(shape, { depth: d, bevelEnabled: true, bevelSegments: 1, bevelSize: .025, bevelThickness: .025 }); geometry.translate(0, 0, -d / 2); return new THREE.Mesh(geometry, material(color, { metalness: .28, roughness: .45 })); };
const cylinder = (r, h, color, options = {}, radial = 12) => new THREE.Mesh(new THREE.CylinderGeometry(r, r * 1.08, h, radial), material(color, options));
const add = (parent, object, name, position = null) => { if (name) object.name = name; if (position) object.position.set(...position); parent.add(object); return object; };
function markOpaque(root) { root.traverse((object) => { if (!object.isMesh) return; const transparent = object.material?.transparent; object.castShadow = !transparent; object.receiveShadow = !transparent; }); return root; }

function makeLeg(parent, side) { const leg = new THREE.Group(); leg.name = `leg-${side < 0 ? 'left' : 'right'}`; const hip = new THREE.Object3D(); hip.position.set(side * .18, .77, 0); hip.name = 'hip'; leg.add(hip); const upper = cylinder(.095, .34, palette.ivory, { metalness: .25 }, 8); upper.position.set(side * .18, .6, 0); upper.name = 'upper-leg'; leg.add(upper); const knee = joint(.115); knee.position.set(side * .18, .43, .04); knee.name = 'knee'; leg.add(knee); const lower = cylinder(.082, .34, palette.charcoal, { metalness: .65, roughness: .4 }, 8); lower.position.set(side * .18, .26, .02); lower.name = 'lower-leg'; leg.add(lower); const ankle = new THREE.Object3D(); ankle.position.set(side * .18, .09, 0); ankle.name = 'ankle'; leg.add(ankle); const boot = box(.34, .16, .42, palette.charcoalDeep, { metalness: .55, roughness: .4 }); boot.position.set(side * .18, .08, 0); boot.name = 'foot'; leg.add(boot); leg.userData.side = side; leg.userData.hip = hip; leg.userData.knee = knee; leg.userData.ankle = ankle; leg.userData.upper = upper; leg.userData.lower = lower; leg.userData.foot = boot; leg.userData.a = .34; leg.userData.b = .34; parent.userData.legs.push(leg.userData); parent.add(leg); return leg; }

export function createPlayerModel() {
  const root = new THREE.Group(); root.name = 'rhea-colossus'; root.userData.feetHeight = 0; root.userData.plateParts = {}; root.userData.legs = [];
  const pelvis = box(.65, .22, .45, palette.charcoal, { metalness: .5, roughness: .42 }); pelvis.position.y = .78; add(root, pelvis, 'pelvis'); makeLeg(root, -1); makeLeg(root, 1);
  const torso = new THREE.Mesh(new THREE.CylinderGeometry(.325, .245, .55, 8), material(palette.charcoal, { metalness: .52, roughness: .48 })); torso.scale.z = .69; torso.position.set(0, 1.12, 0); add(root, torso, 'tapered-shell');
  const chest = box(.4, .3, .06, palette.cobalt, { emissive: palette.cobaltGlow, emissiveIntensity: .45, metalness: .38 }); chest.position.set(0, 1.12, .34); add(root, chest, 'cobalt-core');
  const collar = cylinder(.22, .12, palette.charcoal, { metalness: .65, roughness: .35 }, 8); collar.position.y = 1.43; add(root, collar, 'collar'); const head = new THREE.Mesh(new THREE.CylinderGeometry(.17, .21, .28, 8), material(palette.charcoal, { metalness: .48, roughness: .4 })); head.position.set(0, 1.62, 0); add(root, head, 'helmet'); const visor = box(.28, .07, .06, palette.yellowHot, { emissive: palette.yellowHot, emissiveIntensity: .8 }); visor.position.set(0, 1.63, .2); add(root, visor, 'signal-visor');
  const armGroups = []; [ -1, 1 ].forEach((side) => { const arm = new THREE.Group(); arm.name = `arm-${side < 0 ? 'left' : 'right'}`; arm.position.set(side * .4, 1.34, 0); arm.userData.side = side; add(arm, joint(.105), 'shoulder-joint'); const upper = cylinder(.075, .32, palette.charcoal, { metalness: .66, roughness: .38 }, 8); upper.position.y = -.16; add(arm, upper, 'upper-arm'); const elbow = new THREE.Group(); elbow.name = 'elbow-joint'; elbow.position.y = -.32; add(elbow, joint(.095), 'elbow'); const fore = cylinder(.07, .3, palette.ivory, { metalness: .3, roughness: .5 }, 8); fore.position.y = -.15; add(elbow, fore, 'forearm'); const fist = box(.16, .14, .17, palette.charcoalDeep, { metalness: .6 }); fist.position.set(0, -.33, .06); add(elbow, fist, 'gauntlet'); arm.add(elbow); arm.userData.elbow = elbow; root.add(arm); armGroups.push(arm); });
  const plateData = [[0, armGroups[0], [0, .02, .1], .42, .24, .18], [1, armGroups[1], [0, .02, .1], .42, .24, .18], [2, armGroups[0].userData.elbow, [0, -.15, .12], .25, .28, .16], [3, armGroups[1].userData.elbow, [0, -.15, .12], .25, .28, .16], [4, root, [0, 1.13, .38], .5, .38, .1], [5, root, [0, 1.13, -.38], .5, .38, .1]];
  plateData.forEach(([id, parent, home, w, h, d]) => { const plate = armor(w, h, d, id === 4 ? palette.ivoryBright : palette.ivory); plate.name = `plate-${id}`; plate.userData.plateId = id; plate.userData.homeParent = parent; plate.userData.homePosition = home.slice(); plate.userData.home = home.slice(); plate.position.set(...home); root.userData.plateParts[id] = plate; parent.add(plate); });
  const scarf = box(.05, .28, .035, palette.yellow, { emissive: palette.yellow, emissiveIntensity: .15 }); scarf.position.set(.12, 1.34, .25); scarf.rotation.z = -.16; add(root, scarf, 'signal-scarf');
  return markOpaque(root);
}

function createWalker() { const root = new THREE.Group(); const body = armor(.62, .72, .5, palette.rust); body.position.y = .96; add(root, body, 'walker-shell'); add(root, joint(.22), 'walker-joint', [0, .5, .06]); const eye = box(.3, .1, .08, palette.yellowHot, { emissive: palette.yellowHot, emissiveIntensity: .75 }); eye.position.set(0, 1.28, .3); add(root, eye, 'walker-eye'); [-.22, .22].forEach((x) => { const leg = cylinder(.1, .52, palette.charcoal, { metalness: .65 }, 8); leg.position.set(x, .3, 0); add(root, leg, 'walker-leg'); const foot = box(.28, .12, .38, palette.charcoalDeep); foot.position.set(x, .06, .08); add(root, foot, 'walker-foot'); }); return root; }
function createTurret() { const root = new THREE.Group(); const base = cylinder(.48, .22, palette.charcoal, { metalness: .72, roughness: .35 }, 10); base.position.y = .12; add(root, base, 'turret-base'); const body = cylinder(.34, .5, palette.rust, { metalness: .35 }, 8); body.position.y = .45; add(root, body, 'turret-body'); const eye = box(.34, .16, .08, palette.yellowHot, { emissive: palette.yellowHot, emissiveIntensity: .8 }); eye.position.set(0, .57, .32); add(root, eye, 'turret-eye'); const barrel = cylinder(.1, .85, palette.charcoalDeep, { metalness: .7 }, 8); barrel.rotation.x = Math.PI / 2; barrel.position.set(0, 1, .42); const mount = cylinder(.14, .45, palette.charcoal, { metalness: .7 }, 8); mount.position.set(0, .8, 0); add(root, mount, 'turret-mount'); add(root, barrel, 'turret-barrel'); return root; }
function createDrone() { const root = new THREE.Group(); const core = new THREE.Mesh(new THREE.SphereGeometry(.34, 12, 8), material(palette.cobalt, { emissive: palette.cobaltGlow, emissiveIntensity: .55, metalness: .4 })); core.scale.set(1.2, .55, .8); core.position.y = .9; add(root, core, 'drone-core'); [-1, 1].forEach((side) => { const wing = armor(.7, .12, .32, palette.ivory); wing.position.set(side * .55, .92, 0); wing.rotation.z = side * -.12; add(root, wing, 'drone-wing'); }); const ring = new THREE.Mesh(new THREE.TorusGeometry(.5, .035, 6, 18), material(palette.yellow, { emissive: palette.yellow, emissiveIntensity: .35, metalness: .5 })); ring.rotation.x = Math.PI / 2; ring.position.y = .9; add(root, ring, 'drone-ring'); return root; }

export function createEnemyModel(type = 'walker') { const root = type === 'turret' ? createTurret() : type === 'drone' ? createDrone() : createWalker(); root.name = `enemy-${type}`; root.userData.type = type; return markOpaque(root); }

function bossRam() { const root = createWalker(); root.scale.set(1.7, 1.18, 1.2); const horn = cylinder(.09, 1.05, palette.yellow, { metalness: .5 }, 8); horn.rotation.z = Math.PI / 2; horn.position.set(.72, .98, .1); add(root, horn, 'ram-horn'); const shoulder = armor(.8, .4, .32, palette.ivoryBright); shoulder.position.set(0, 1.02, 0); add(root, shoulder, 'ram-shoulder'); const core = cylinder(.22, .08, palette.cobaltGlow, { emissive: palette.cobaltGlow, emissiveIntensity: 1, metalness: .2 }, 8); core.rotation.x = Math.PI / 2; core.position.set(0, .68, .48); add(root, core, 'boss-core'); return root; }
function bossSpindle() { const root = new THREE.Group(); const base = cylinder(.58, .18, palette.charcoalDeep, { metalness: .7, roughness: .36 }, 10); base.position.y = .09; add(root, base, 'spindle-base'); const stem = cylinder(.24, .42, palette.charcoal, { metalness: .65 }, 8); stem.position.y = .3; add(root, stem, 'spindle-stem'); const core = cylinder(.8, 1.65, palette.violet, { emissive: palette.cobaltGlow, emissiveIntensity: .35, metalness: .55 }, 8); core.position.y = 1.2; add(root, core, 'spindle-core'); const weak = cylinder(.22, .08, palette.cobaltGlow, { emissive: palette.cobaltGlow, emissiveIntensity: 1, metalness: .2 }, 8); weak.rotation.x = Math.PI / 2; weak.position.set(0, .95, .82); add(root, weak, 'boss-core'); for (let i = 0; i < 4; i++) { const arm = box(1.95, .14, .22, palette.yellow, { metalness: .6 }); arm.position.y = .5 + i * .5; arm.rotation.z = i % 2 ? .14 : -.14; add(root, arm, `spindle-arm-${i}`); } add(root, joint(.5, palette.charcoalDeep), 'spindle-joint', [0, 2.12, 0]); return root; }
function bossCrown() { const root = new THREE.Group(); const body = armor(1.5, 1.8, .85, palette.ivoryBright); body.position.y = 1.15; add(root, body, 'crown-shell'); [-.52, .52].forEach((x) => { const foot = box(.34, .24, .4, palette.charcoalDeep, { metalness: .62 }); foot.position.set(x, .12, .02); add(root, foot, 'crown-foot'); }); const core = cylinder(.38, .1, palette.cobaltGlow, { emissive: palette.cobaltGlow, emissiveIntensity: 1, metalness: .2 }, 8); core.rotation.x = Math.PI / 2; core.position.set(0, .95, .51); add(root, core, 'crown-core'); for (let i = -1; i <= 1; i++) { const spike = armor(.38, .8, .28, palette.yellow); spike.position.set(i * .48, 2.22 + Math.abs(i) * .1, 0); spike.rotation.z = i * .18; add(root, spike, `crown-spike-${i}`); } [-.62, .62].forEach((x) => { const arm = cylinder(.15, 1.1, palette.charcoal, { metalness: .65 }, 8); arm.rotation.z = x < 0 ? -.32 : .32; arm.position.set(x, 1.2, 0); add(root, arm, 'crown-arm'); }); return root; }
export function createBossModel(type = 'ram') { const root = type === 'spindle' ? bossSpindle() : type === 'crown' ? bossCrown() : bossRam(); root.name = `boss-${type}`; root.userData.type = type; const shield = new THREE.Mesh(new THREE.TorusGeometry(type === 'crown' ? 1.05 : .9, .045, 6, 24), material(palette.cobaltGlow, { transparent: true, opacity: .5, emissive: palette.cobaltGlow, emissiveIntensity: .8, metalness: .15 })); shield.rotation.x = Math.PI / 2; shield.position.y = type === 'spindle' ? 1.25 : 1.1; shield.name = 'boss-shield'; root.add(shield); root.userData.shield = shield; return markOpaque(root); }

export function createPlatformModel(platform) { const root = new THREE.Group(); root.name = `platform-${platform?.id || 'platform'}`; const width = Math.max(.5, Number(platform?.width) || 4), top = Number(platform?.y) || 0; const deck = box(width, .18, .9, palette.ivory, { metalness: .25, roughness: .58 }); deck.position.set(width / 2, top - .09, 0); add(root, deck, 'platform-deck'); const beam = box(width + .18, .1, .16, palette.yellow, { emissive: palette.yellow, emissiveIntensity: .15, metalness: .45 }); beam.position.set(width / 2, top - .2, .38); add(root, beam, 'platform-edge'); if (top === 0) { const hull = box(width, 4, 1.45, 0x26364b, { metalness: .45, roughness: .7 }); hull.position.set(width / 2, -2.24, -.24); add(root, hull, 'foundation-hull'); for (let x = .25; x < width; x += 3.5) { const rib = box(.13, 3.95, .18, palette.steel, { metalness: .6 }); rib.position.set(x, -2.23, .56); add(root, rib, 'foundation-rib'); const braceWidth = Math.min(3.15, width - x - .15); if (braceWidth > .5) { const brace = box(Math.hypot(braceWidth, 2), .10, .12, palette.charcoal, { metalness: .6 }); brace.position.set(x + braceWidth / 2, -1.45, .6); brace.rotation.z = Math.atan2(2, braceWidth); add(root, brace, 'foundation-brace'); } } } if (top > .3) for (const x of [.28, width - .28]) { const pillar = box(.18, top, .22, palette.charcoal, { metalness: .58 }); pillar.position.set(x, top / 2, -.12); add(root, pillar, 'platform-support'); } return markOpaque(root); }

export function createRelayModel(active = false) { const root = new THREE.Group(); const base = cylinder(.34, .16, palette.charcoal, { metalness: .65 }, 10); base.position.y = .08; add(root, base, 'relay-base'); const mast = cylinder(.08, .8, palette.ivory, { metalness: .3 }, 8); mast.position.y = .52; add(root, mast, 'relay-mast'); const halo = new THREE.Mesh(new THREE.TorusGeometry(.34, .045, 6, 18), material(active ? palette.cobaltGlow : palette.yellow, { emissive: active ? palette.cobaltGlow : palette.yellow, emissiveIntensity: active ? 1 : .3, metalness: .55 })); halo.rotation.x = Math.PI / 2; halo.position.y = .78; halo.name = 'relay-halo'; root.add(halo); return markOpaque(root); }

export function disposeModel(root) { if (!root) return; const geometries = new Set(), materials = new Set(); root.traverse((object) => { if (object.geometry) geometries.add(object.geometry); const list = Array.isArray(object.material) ? object.material : object.material ? [object.material] : []; list.forEach((entry) => materials.add(entry)); }); geometries.forEach((entry) => entry.dispose()); materials.forEach((entry) => entry.dispose()); root.clear(); }
