import * as THREE from 'three';
import { createPlayerModel, createEnemyModel, createBossModel, createPlatformModel, createRelayModel, disposeModel, palette } from './models.js';
import { getLevel } from './levels.js';
import { createSkyTexture, createFactoryBackdrop } from './environment.js';

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const phaseOffset = (value) => { if (Number.isFinite(value)) return value; const text = String(value ?? ''); let hash = 0; for (let i = 0; i < text.length; i++) hash = (hash * 31 + text.charCodeAt(i)) | 0; return (Math.abs(hash) % 997) / 113; };
const placeBone = (bone, from, to) => { const direction = to.clone().sub(from), length = Math.max(.001, direction.length()); bone.position.copy(from).add(to).multiplyScalar(.5); bone.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), direction.normalize()); const baseLength = bone.geometry?.parameters?.height || length; bone.scale.set(1, length / baseLength, 1); };
const projectileVisual = (projectile) => { if (projectile.type === 'beam') return new THREE.Mesh(new THREE.BoxGeometry(1, .28, .16), opaque(palette.yellow, { emissive: palette.yellow, emissiveIntensity: .9, metalness: .2 })); if (projectile.type === 'wave') return new THREE.Mesh(new THREE.TorusGeometry(.45, .1, 8, 20), opaque(palette.yellow, { emissive: palette.yellow, emissiveIntensity: .85, metalness: .2 })); const group = new THREE.Group(); const bolt = new THREE.Mesh(new THREE.SphereGeometry(.1, 8, 6), opaque(palette.cobaltGlow, { emissive: palette.cobaltGlow, emissiveIntensity: .95, metalness: .2 })); group.add(bolt); const tail = new THREE.Mesh(new THREE.BoxGeometry(.34, .055, .055), opaque(palette.cobalt, { emissive: palette.cobaltGlow, emissiveIntensity: .45, metalness: .2 })); tail.position.x = -Math.sign(Number(projectile.vx) || 1) * .17; group.add(tail); return group; };
const opaque = (color, options = {}) => new THREE.MeshStandardMaterial({ color, roughness: options.roughness ?? .72, metalness: options.metalness ?? .2, emissive: options.emissive ?? 0, emissiveIntensity: options.emissiveIntensity ?? 0, transparent: !!options.transparent, opacity: options.opacity ?? 1 });
const slab = (w, h, d, color, options) => new THREE.Mesh(new THREE.BoxGeometry(w, h, d), opaque(color, options));

class CastoffScene {
  constructor(container) {
    this.host = container; this.canvas = container?.tagName === 'CANVAS' ? container : container?.querySelector?.('canvas') || (typeof document !== 'undefined' ? document.createElement('canvas') : null); if (!this.canvas) throw new Error('Castoff Colossus requires a canvas'); if (container?.tagName !== 'CANVAS' && this.canvas.parentElement !== container && container?.appendChild) container.appendChild(this.canvas);
    this.renderer = new THREE.WebGLRenderer({ canvas: this.canvas, antialias: false, powerPreference: 'high-performance' }); this.renderer.outputColorSpace = THREE.SRGBColorSpace; this.renderer.toneMapping = THREE.ACESFilmicToneMapping; this.renderer.toneMappingExposure = .98;
    let rendererName = ''; try { const gl = this.renderer.getContext(), ext = gl.getExtension('WEBGL_debug_renderer_info'); rendererName = ext ? gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) : gl.getParameter(gl.RENDERER); } catch (_) {} this.software = /swiftshader|llvmpipe|software|mesa/i.test(`${rendererName} ${globalThis.navigator?.userAgent || ''}`); this.pixelBudget = this.software ? 400000 : 1500000; this.renderer.shadowMap.enabled = !this.software;
    this.scene = new THREE.Scene(); this.skyTexture = createSkyTexture(); this.scene.background = this.skyTexture || new THREE.Color(0x263c61); this.scene.fog = new THREE.Fog(0x405674, 22, 68); this.world = new THREE.Group(); this.scene.add(this.world); this.levelDecor = new THREE.Group(); this.levelDecor.name = 'factory-level-decor'; this.world.add(this.levelDecor); this.actorLayer = new THREE.Group(); this.actorLayer.name = 'actors'; this.world.add(this.actorLayer); this.plateLayer = new THREE.Group(); this.plateLayer.name = 'flying-armor'; this.world.add(this.plateLayer); this.effectLayer = new THREE.Group(); this.effectLayer.name = 'impact-effects'; this.world.add(this.effectLayer);
    this.camera = new THREE.PerspectiveCamera(48, 16 / 9, .1, 100); this.camera.position.set(0, 4.1, 17); this.camera.lookAt(0, 2.25, 0); this.scene.add(this.camera); this.addLights(); this.player = createPlayerModel(); this.actorLayer.add(this.player); this.enemyMeshes = new Map(); this.projectileMeshes = new Map(); this.relayMeshes = new Map(); this.effects = []; this.levelId = null; this.levelLength = 64; this.cameraX = 0; this.elapsed = 0; this.frame = 0; this.lastEvents = null; this.run = null; this.view = {};
    this.resize(); this.resizeObserver = globalThis.ResizeObserver ? new ResizeObserver(() => this.resize()) : null; this.resizeObserver?.observe(this.host || this.canvas);
  }
  addLights() { this.scene.add(new THREE.HemisphereLight(0xa6bfe0, 0x536780, 1.9)); const key = new THREE.DirectionalLight(0xffe8b0, 2.2); key.position.set(-9, 14, 12); key.castShadow = !this.software; key.shadow.mapSize.set(768, 768); key.shadow.camera.left = -18; key.shadow.camera.right = 18; key.shadow.camera.top = 12; key.shadow.camera.bottom = -3; key.shadow.camera.near = .5; key.shadow.camera.far = 80; this.scene.add(key); this.scene.add(key.target); this.keyLight = key; }
  markShadows(root) { root?.traverse((object) => { if (object.isMesh) { if (object.userData.background) { object.castShadow = false; object.receiveShadow = false; return; } const transparent = object.material?.transparent; object.castShadow = !this.software && !transparent; object.receiveShadow = !transparent; } }); }
  addFactoryDecor(length, platforms = []) { const backdrop = createFactoryBackdrop({ length, platforms }); this.levelDecor.add(backdrop); const ground = (x) => platforms.some((item) => Number(item.y) === 0 && x >= item.x && x <= item.x + item.width); for (const item of platforms.filter((entry) => Number(entry.y) === 0)) { const rail = slab(item.width, .05, .08, palette.yellow, { emissive: palette.yellow, emissiveIntensity: .25, metalness: .55 }); rail.position.set(item.x + item.width / 2, .015, .3); this.levelDecor.add(rail); } for (let x = 2; x < length; x += 8) { const pillar = slab(.16, 6.2, .18, palette.charcoal, { metalness: .65, roughness: .42 }); pillar.position.set(x, 3.05, -.92); this.levelDecor.add(pillar); const brace = slab(1.8, .12, .12, palette.cobalt, { emissive: palette.cobalt, emissiveIntensity: .18, metalness: .5 }); brace.position.set(x + .8, 4.8, -.92); brace.rotation.z = -.24; this.levelDecor.add(brace); } for (let x = 5; x < length; x += 13) if (ground(x)) { const tank = new THREE.Mesh(new THREE.CylinderGeometry(.58, .58, 2.4, 12), opaque(palette.steel, { metalness: .7, roughness: .35 })); tank.rotation.z = Math.PI / 2; tank.position.set(x, 2.2, -1.05); this.levelDecor.add(tank); for (const side of [-.78, .78]) { const support = slab(.14, 2.2, .18, palette.charcoal, { metalness: .65, roughness: .44 }); support.position.set(x + side, 1.1, -1.05); this.levelDecor.add(support); } const stripe = slab(.08, 1.4, .03, palette.yellow, { emissive: palette.yellow, emissiveIntensity: .25 }); stripe.position.set(x, 2.2, -.45); this.levelDecor.add(stripe); } }
  rebuildLevel(run) { const level = getLevel(run?.levelId); this.levelId = level?.id || run?.levelId || null; this.levelLength = Number(level?.length) || 64; const platforms = Array.isArray(level?.platforms) ? level.platforms : []; this.levelDecor.children.slice().forEach((child) => { this.levelDecor.remove(child); disposeModel(child); }); for (const visual of this.enemyMeshes.values()) { this.actorLayer.remove(visual); disposeModel(visual); } for (const visual of this.projectileMeshes.values()) { this.actorLayer.remove(visual); disposeModel(visual); } this.enemyMeshes.clear(); this.projectileMeshes.clear(); this.relayMeshes.clear(); this.effects.forEach((effect) => { this.effectLayer.remove(effect.root); disposeModel(effect.root); }); this.effects.length = 0; this.addFactoryDecor(this.levelLength, platforms); platforms.forEach((platform) => { const visual = createPlatformModel(platform); visual.position.x = Number(platform.x) || 0; this.levelDecor.add(visual); this.markShadows(visual); }); (Array.isArray(run?.relays) ? run.relays : []).forEach((relay) => { const visual = createRelayModel(!!relay.active); visual.position.set(Number(relay.x) || 0, (Number(relay.y) || 0) - .9, .05); visual.userData.relayId = relay.id; this.levelDecor.add(visual); this.relayMeshes.set(relay.id, visual); this.markShadows(visual); }); const exit = slab(.18, 3.4, .5, palette.yellow, { emissive: palette.yellow, emissiveIntensity: .2, metalness: .45 }); exit.position.set(this.levelLength - 1.2, 1.7, .1); exit.name = 'exit-beacon'; this.levelDecor.add(exit); const exitTop = slab(1.2, .12, .48, palette.cobalt, { emissive: palette.cobalt, emissiveIntensity: .3 }); exitTop.position.set(this.levelLength - 1.2, 3.35, .1); this.levelDecor.add(exitTop); this.markShadows(this.levelDecor); this.lastEvents = null; }
  syncActors(run) { const enemies = Array.isArray(run?.enemies) ? run.enemies : []; for (const enemy of enemies) { let visual = this.enemyMeshes.get(enemy.id); if (!visual) { visual = createEnemyModel(enemy.type); visual.userData.enemyId = enemy.id; this.enemyMeshes.set(enemy.id, visual); this.actorLayer.add(visual); this.markShadows(visual); } visual.visible = enemy.alive !== false; visual.position.set(Number(enemy.x) || 0, Number(enemy.y) || 0, enemy.type === 'drone' ? .15 : .02); visual.rotation.y = Number(enemy.facing) < 0 ? -Math.PI / 2 : Math.PI / 2; const offset = phaseOffset(enemy.phase), bob = enemy.type === 'drone' ? Math.sin(this.elapsed * 3 + offset) * .12 : 0, telegraph = String(enemy.phase || '') === 'telegraph'; visual.position.y += bob; visual.rotation.z = (enemy.type === 'walker' ? Math.sin(this.elapsed * 5 + offset) * .03 : 0) + (telegraph ? Math.sin(this.elapsed * 12 + offset) * .07 : 0); } for (const [id, visual] of this.enemyMeshes) if (!enemies.some((enemy) => enemy.id === id) && id !== run?.boss?.id) visual.visible = false;
    const boss = run?.boss; if (boss) { let visual = this.enemyMeshes.get(boss.id); if (!visual) { visual = createBossModel(boss.type); visual.userData.enemyId = boss.id; this.enemyMeshes.set(boss.id, visual); this.actorLayer.add(visual); this.markShadows(visual); } visual.visible = boss.alive !== false; visual.position.set(Number(boss.x) || 0, Number(boss.y) || 0, .03); const bossFacing = (Number(run.player?.x) || 0) < (Number(boss.x) || 0) ? -1 : 1; visual.rotation.y = bossFacing < 0 ? -Math.PI / 2 : Math.PI / 2; visual.rotation.z = boss.tell ? Math.sin(this.elapsed * 8) * .035 : 0; const phase = String(boss.phase || 'dormant'), shield = visual.userData.shield; if (shield) { shield.visible = visual.visible && phase !== 'recovery' && phase !== 'dead'; shield.material.opacity = phase === 'telegraph' ? .28 : .52; } const core = visual.getObjectByName('boss-core') || visual.getObjectByName('crown-core'); if (core) core.material.emissiveIntensity = phase === 'recovery' ? 1.7 : phase === 'dead' ? .08 : .55; }
  }
  syncRelays(run) { (Array.isArray(run?.relays) ? run.relays : []).forEach((relay) => { const visual = this.relayMeshes.get(relay.id); if (!visual) return; const halo = visual.getObjectByName('relay-halo'); if (halo) { const active = !!relay.active; halo.material.color.set(active ? palette.cobaltGlow : palette.yellow); halo.material.emissive.set(active ? palette.cobaltGlow : palette.yellow); halo.material.emissiveIntensity = active ? 1 : .3; } }); }
  syncPlates(run, dt = 0) { const plates = Array.isArray(run?.plates) ? run.plates : []; const parts = this.player.userData.plateParts; for (let id = 0; id < 6; id++) { const state = plates.find((plate) => Number(plate.id) === id); const mesh = parts[id]; if (!mesh || !state) continue; const attached = state.status === 'attached', homeParent = mesh.userData.homeParent || this.player, homePosition = mesh.userData.homePosition || mesh.userData.home; if (attached) { if (mesh.parent !== homeParent) homeParent.add(mesh); mesh.position.set(...homePosition); mesh.rotation.set(0, 0, 0); mesh.visible = true; } else { if (mesh.parent !== this.plateLayer) this.plateLayer.add(mesh); mesh.visible = true; const sx = Number.isFinite(Number(state.x)) ? Number(state.x) : this.player.position.x, sy = Number.isFinite(Number(state.y)) ? Number(state.y) : this.player.position.y + .95; mesh.position.set(sx, sy, .12); mesh.rotation.z += dt * 4; } } }
  updatePlayer(run, dt) { const state = run?.player; if (!state) return; const x = Number(state.x) || 0, y = Number(state.y) || 0; this.player.position.set(x, y, .12); const facing = Number(state.facing) < 0 ? -1 : 1; this.player.scale.x = 1; this.player.rotation.y = facing > 0 ? Math.PI / 2 : -Math.PI / 2; const speed = Math.abs(Number(state.vx) || 0); const moving = speed > .08; const phase = this.elapsed * 9; this.player.userData.legs.forEach((leg, index) => { const stride = moving ? Math.sin(phase + index * Math.PI) : 0, ankleY = .14 + Math.max(0, stride) * .12, footZ = moving ? stride * .2 : 0, side = leg.side, hip = new THREE.Vector3(side * .18, .77, 0), foot = new THREE.Vector3(side * .18, ankleY, footZ), dy = foot.y - hip.y, dz = foot.z - hip.z, distance = clamp(Math.hypot(dy, dz), .05, leg.a + leg.b - .001), t = (leg.a * leg.a - leg.b * leg.b + distance * distance) / (2 * distance), bend = Math.sqrt(Math.max(0, leg.a * leg.a - t * t)), knee = new THREE.Vector3(side * .18, hip.y + dy / distance * t + dz / distance * bend, hip.z + dz / distance * t - dy / distance * bend); leg.hip.position.copy(hip); leg.knee.position.copy(knee); leg.ankle.position.copy(foot); leg.foot.position.set(foot.x, foot.y - .06, foot.z); leg.foot.rotation.x = 0; placeBone(leg.upper, hip, knee); placeBone(leg.lower, knee, foot); }); const arms = this.player.children.filter((child) => child.name.startsWith('arm-')); const striking = Number(state.punchTime) > 0 || Number(state.fireCooldown) > .16; arms.forEach((arm, index) => { arm.rotation.x = striking ? (index ? -.86 : -1.1) : moving ? Math.sin(phase + index * Math.PI) * .08 : 0; if (arm.userData.elbow) arm.userData.elbow.rotation.x = striking ? -.35 : 0; }); this.syncPlates(run, dt); }
  syncProjectiles(run) { const list = Array.isArray(run?.projectiles) ? run.projectiles : []; for (const projectile of list) { let visual = this.projectileMeshes.get(projectile.id); if (!visual) { visual = projectileVisual(projectile); visual.userData.projectileId = projectile.id; this.projectileMeshes.set(projectile.id, visual); this.actorLayer.add(visual); } visual.visible = true; visual.position.set(Number(projectile.x) || 0, projectile.type === 'wave' ? .45 : Number(projectile.y) || 0, .3); if (projectile.type === 'beam') { visual.scale.set(Math.max(1, Number(projectile.length) || 5.5), 1, 1); visual.rotation.z = 0; } else if (projectile.type === 'wave') visual.scale.set(1, 1, 1); else visual.scale.setScalar(1); } for (const [id, visual] of this.projectileMeshes) if (!list.some((projectile) => projectile.id === id)) { this.actorLayer.remove(visual); disposeModel(visual); this.projectileMeshes.delete(id); } }
  spawnImpact(event) { const root = new THREE.Group(); root.name = 'hit-spark'; const color = event.type === 'armor-return' || event.type === 'recall' ? palette.cobaltGlow : palette.yellowHot; for (let i = 0; i < 5; i++) { const spark = new THREE.Mesh(new THREE.IcosahedronGeometry(.055, 0), opaque(color, { emissive: color, emissiveIntensity: 1, metalness: .1, transparent: true })); spark.position.set(Math.cos(i * 1.256) * .18, Math.sin(i * 1.256) * .18, .2); root.add(spark); } root.position.set(Number(event.x) || this.player.position.x, Number(event.y) || this.player.position.y + 1, .35); this.effectLayer.add(root); this.effects.push({ root, age: 0 }); }
  processEvents(run, view) { const events = Array.isArray(view?.events) ? view.events : run?.events; if (!events || events === this.lastEvents) return; this.lastEvents = events; events.forEach((event) => { if (['hit', 'shot', 'land', 'armor-return', 'recall', 'relay', 'enemy-down', 'boss-open', 'clear'].includes(event.type)) this.spawnImpact(event); }); }
  updateEffects(dt) { for (let i = this.effects.length - 1; i >= 0; i--) { const effect = this.effects[i]; effect.age += dt; effect.root.scale.setScalar(1 + effect.age * 2); effect.root.children.forEach((spark) => { spark.position.multiplyScalar(1 + dt * 4); spark.material.opacity = 1 - effect.age / .38; }); if (effect.age > .38) { this.effectLayer.remove(effect.root); disposeModel(effect.root); this.effects.splice(i, 1); } } }
  updateCamera(run, view, dt) { const x = Number(run?.player?.x) || this.cameraX; const lookahead = clamp(Number(run?.player?.vx) || 0, -3, 3) * .25; const fov = this.camera.aspect < .7 ? 62 : 48; if (this.camera.fov !== fov) { this.camera.fov = fov; this.camera.updateProjectionMatrix(); } const distance = 17.1, viewportHalf = distance * Math.tan(THREE.MathUtils.degToRad(fov / 2)) * this.camera.aspect, margin = 1.3, minCenter = Math.min(this.levelLength / 2, viewportHalf - margin), maxCenter = Math.max(this.levelLength / 2, this.levelLength - viewportHalf + margin); const targetX = clamp(x + lookahead, Math.max(0, minCenter), maxCenter); this.cameraX += (targetX - this.cameraX) * Math.min(1, dt * 6); const shake = view?.shake === true ? .12 : Number(view?.shake) || 0; const jitter = shake ? Math.sin(this.elapsed * 77) * shake : 0; this.camera.position.set(this.cameraX + jitter, 4.2 + jitter * .2, 17); this.camera.lookAt(this.cameraX + jitter * .25, 2.25, 0); this.camera.updateMatrixWorld(true); }
  update(run = null, dt = 1 / 60, view = {}) { const delta = clamp(Number(dt) || 0, 0, .05); this.elapsed += delta; this.run = run; this.view = view || {}; const nextLevel = run?.levelId || view?.levelId || null; if (run && nextLevel !== this.levelId) this.rebuildLevel(run); if (run) { this.updatePlayer(run, delta); this.syncActors(run); this.syncRelays(run); this.syncProjectiles(run); this.processEvents(run, view); if (!this.software && this.keyLight) { const px = Number(run.player?.x) || 0; this.keyLight.position.set(px - 9, 14, 12); this.keyLight.target.position.set(px, 0, 0); this.keyLight.target.updateMatrixWorld(); } } this.updateEffects(delta); this.updateCamera(run, view, delta); this.render(); }
  render() { this.renderer.render(this.scene, this.camera); this.frame++; }
  resize() { const width = this.canvas.clientWidth || this.host?.clientWidth || 960, height = this.canvas.clientHeight || this.host?.clientHeight || 540; this.renderer.setPixelRatio(Math.min(2, globalThis.devicePixelRatio || 1, Math.sqrt(this.pixelBudget / Math.max(1, width * height)))); this.renderer.setSize(width, height, false); this.camera.aspect = width / Math.max(1, height); this.camera.updateProjectionMatrix(); }
  get stats() { const render = this.renderer.info.render, memory = this.renderer.info.memory, plates = Array.isArray(this.run?.plates) ? this.run.plates.filter((plate) => plate.status === 'attached').length : 0; return { software: this.software, pixels: (this.canvas.width || 0) * (this.canvas.height || 0), frames: this.frame, drawCalls: render.calls, triangles: render.triangles, levelId: this.levelId, attachedPlates: plates, geometries: memory.geometries }; }
  dispose() { this.resizeObserver?.disconnect(); this.resizeObserver = null; disposeModel(this.world); this.skyTexture?.dispose(); this.skyTexture = null; this.renderer.dispose(); }
}

export function createScene(container) { return new CastoffScene(container); }
export default createScene;
